const properties: Array<string> = [
  "all_products_count",
  "all_tags",
  "all_types",
  "all_vendors",
  "current_type",
  "current_vendor",
  "default_sort_by",
  "description",
  "featured_image",
  "filters",
  "handle",
  "id",
  "image",
  "metafields",
  "next_product",
  "previous_product",
  "products",
  "products_count",
  "published_at",
  "sort_by",
  "sort_options",
  "tags",
  "template_suffix",
  "title",
  "url",
];

export default properties;
