const properties: Array<string> = [
  "accepts_marketing",
  "addresses",
  "addresses_count",
  "b2b?",
  "company_available_locations",
  "current_company",
  "current_location",
  "default_address",
  "email",
  "first_name",
  "has_account",
  "id",
  "last_name",
  "last_order",
  "name",
  "orders",
  "orders_count",
  "phone",
  "tags",
  "tax_exempt",
  "total_spent",
];

export default properties;
